Traceback (most recent call last):
  File "test.py", line 39, in <module>
    OUTPUT_DIRECTORY = 'input_files/trash_outputs/trash')
  File "/Users/mojtabahaghighatlari/Box Sync/Hachmann_Group/7_MLpackages/cheml/CheML/cheml/wrappers/engine.py", line 458, in run
    wrapper.call()
  File "/Users/mojtabahaghighatlari/Box Sync/Hachmann_Group/7_MLpackages/cheml/CheML/cheml/wrappers/engine.py", line 356, in call
    cmli.run()
  File "/Users/mojtabahaghighatlari/Box Sync/Hachmann_Group/7_MLpackages/cheml/CheML/cheml/wrappers/base.py", line 30, in run
    self.fit()
  File "/Users/mojtabahaghighatlari/Box Sync/Hachmann_Group/7_MLpackages/cheml/CheML/cheml/wrappers/pandas_pd/pandas_wrapper.py", line 34, in fit
    self.set_value(token, df)
  File "/Users/mojtabahaghighatlari/Box Sync/Hachmann_Group/7_MLpackages/cheml/CheML/cheml/wrappers/base.py", line 128, in set_value
    if str(type(value)) in self.ouputs[token].types or \
AttributeError: 'read_table' object has no attribute 'ouputs'
